- name: template nginx.conf
  become: yes
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy archive with location and upstream configuration
  unarchive:
    src: configuration.tar.gz
    dest: /tmp

- name: copy new configuration and backup old
  become: yes
  copy:
    remote_src: yes
    src: /tmp/{{ item }}
    dest: /etc/nginx/conf.d/
    backup: yes
  loop:
  - location.conf
  - upstreams.conf

- name: check nginx configuration
  become: yes
  command: "nginx -t"
  register: config_validation

- name: reload nginx if config valid
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes
  when: config_validation is ok
